included: # paths to include during linting. `--path` is ignored if present.
  - PopcornTime
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
disabled_rules:
  - line_length
  - variable_name
  - cyclomatic_complexity
  - nesting
